version: '1.0'
services:
  mongo:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
  backend:
    build: .
    container_name: "always_backend"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_URL: "mongodb://mongodb:27017"
volumes:
  mongodb_data: